# Rótulos em português — dataset COCO (80 classes, padrão YOLO11n)
CLASS_LABELS_PT: dict[str, str] = {
    "person": "Pessoa",
    "bicycle": "Bicicleta",
    "car": "Carro",
    "motorcycle": "Motocicleta",
    "airplane": "Avião",
    "bus": "Ônibus",
    "train": "Trem",
    "truck": "Caminhão",
    "boat": "Barco",
    "traffic light": "Semáforo",
    "fire hydrant": "Hidrante",
    "stop sign": "Placa de pare",
    "parking meter": "Parquímetro",
    "bench": "Banco",
    "bird": "Pássaro",
    "cat": "Gato",
    "dog": "Cachorro",
    "horse": "Cavalo",
    "sheep": "Ovelha",
    "cow": "Vaca",
    "elephant": "Elefante",
    "bear": "Urso",
    "zebra": "Zebra",
    "giraffe": "Girafa",
    "backpack": "Mochila",
    "umbrella": "Guarda-chuva",
    "handbag": "Bolsa",
    "tie": "Gravata",
    "suitcase": "Mala",
    "frisbee": "Frisbee",
    "sports ball": "Bola esportiva",
    "kite": "Pipa",
    "baseball bat": "Taco de beisebol",
    "baseball glove": "Luva de beisebol",
    "skateboard": "Skate",
    "surfboard": "Prancha de surf",
    "tennis racket": "Raquete de tênis",
    "bottle": "Garrafa",
    "wine glass": "Taça de vinho",
    "cup": "Xícara",
    "fork": "Garfo",
    "knife": "Faca",
    "spoon": "Colher",
    "bowl": "Tigela",
    "banana": "Banana",
    "apple": "Maçã",
    "sandwich": "Sanduíche",
    "orange": "Laranja",
    "broccoli": "Brócolis",
    "carrot": "Cenoura",
    "hot dog": "Cachorro-quente",
    "pizza": "Pizza",
    "donut": "Rosquinha",
    "cake": "Bolo",
    "chair": "Cadeira",
    "couch": "Sofá",
    "potted plant": "Vaso de planta",
    "bed": "Cama",
    "dining table": "Mesa de jantar",
    "toilet": "Vaso sanitário",
    "tv": "TV",
    "laptop": "Notebook",
    "mouse": "Mouse",
    "remote": "Controle remoto",
    "keyboard": "Teclado",
    "cell phone": "Celular",
    "microwave": "Micro-ondas",
    "oven": "Forno",
    "toaster": "Torradeira",
    "sink": "Pia",
    "refrigerator": "Geladeira",
    "book": "Livro",
    "clock": "Relógio",
    "vase": "Vaso",
    "scissors": "Tesoura",
    "teddy bear": "Urso de pelúcia",
    "hair drier": "Secador de cabelo",
    "toothbrush": "Escova de dentes",
}


def class_label_pt(name: str | None) -> str:
    if not name:
        return "—"
    return CLASS_LABELS_PT.get(name, name.replace("_", " ").title())
